[package]
name = "im-sebastian"
version = "0.1.0"
edition = "2024"
license = "MIT"
authors = ["mkaraki"]
description = "Simple image read/convert library"
readme = "README.md"

[features]
default = [
    "lossy_webp",
    "fast_image_resize",
    "rayon",
]

full_format = [
    "lepton",
    "lossy_webp",
    "fast_image_resize",
]

lepton = ["dep:lepton_jpeg"]
lossy_webp = ["dep:webp"]

fast_image_resize = ["dep:fast_image_resize"]
rayon = ["fast_image_resize/rayon", "image/rayon"]

[dependencies]
cfg-if = "1.0.4"
fast_image_resize = { version = "5.4.0", optional = true, features = ["image"] }
image = { version = "0.25.9", default-features = false, features = ["default-formats"] }
lepton_jpeg = { version = "0.5.5", optional = true }
webp = { version = "0.3.1", optional = true }
opentelemetry = { version = "0.31.0", default-features = false, features = ["trace"] }
